Fix get_latest_version procedure that were showing bad information
freeCodeCamp/devdocs pull request #1296
Opened 2020-11-09 16:07 UTC by MasterEnoc

- markdown: update scraper and fix get_latest_version

- rails: fix get_latest_version, it was showing an outdated
  version as the latest version

- apache: fix get_latest_version, it was showing and
  outdated version as the latest version

- cakephp: fix get_latest_version, it was showing and
  outdated version as the latest version

2020-11-13 23:43 UTC, simon04 requested changes
Can you please undo the changes to markdown (see my comment)? The other changes are great.

2020-11-13 23:43 UTC, simon04 commented on lib/docs/scrapers/markdown.rb
> +    self.base_url = 'https://daringfireball.net/projects/markdown/syntax'
I don't think the Markdown specs are versioned. AFAIK, version 1.0.1 refers to the Perl reference implementation…

2020-11-14 02:36 UTC, MasterEnoc commented
should I undo all the changes of markdown? I can leave `self.release = '1.0.0'` to avoid showing it in outdated documentation

2020-11-14 10:04 UTC, simon04 commented
I'd not invent a versioning number when the specification does not provide any. Just my 2¢…

2020-11-14 17:21 UTC, MasterEnoc commented
Fixed, please proceed to review it

2020-11-14 18:11 UTC, simon04 approved these changes

2020-11-14 18:12 UTC, merged