Update Gcc scraper
freeCodeCamp/devdocs pull request #1325
Opened 2020-11-16 00:39 UTC by MasterEnoc

- Add 10.2.0 version

- Update previous versions

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

2020-11-17 07:04 UTC, simon04 requested changes

2020-11-17 07:04 UTC, simon04 commented on lib/docs/scrapers/gnu/gcc.rb
> +      self.release = '8.4.0'
Updating all previous releases requires (me) to download and re-generate all docs (for a consistent state). Unless there are substantial changes to older versions, please refrain from updating those versions (maybe except for the second to newest one). Thank you!

2020-11-18 01:03 UTC, MasterEnoc commented
Fixed, proceed to review it

2020-11-18 19:46 UTC, simon04 approved these changes
Thank you!

2020-11-18 19:47 UTC, merged