Added Documentation for React-bootstrap
freeCodeCamp/devdocs pull request #1486
Opened 2021-02-20 16:54 UTC by dohsimpson

If you’re adding a new scraper, please ensure that you have:

- [x] Tested the scraper on a local copy of DevDocs
- [x] Ensured that the docs are styled similarly to other docs on DevDocs

- [x] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [x] `16.png`: a 16×16 pixel icon for the doc
  - [x] `16@2x.png`: a 32×32 pixel icon for the doc
  - [x] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

2021-02-22 20:08 UTC, simon04 requested changes
Thank you. Please see my review comments.

2021-02-22 20:08 UTC, simon04 commented on lib/docs/filters/react_bootstrap/clean_html.rb
> +          code['style'] = code['style'] + '; border: solid 1px;'
- [ ] The `.position-relative` does not seem very specific for a code fragment. What about using `css('pre').ancestors('.position-relative').first`?
- [ ] Please extract the raw JSX code from the code fragment and rely on DevDoc's Prism.js syntax highlighting. See other scrapers for some examples. Most of them follow a patter such as: 

```ruby
node.content = node.content
node['data-language'] = 'jsx'
```

2021-02-22 20:08 UTC, simon04 commented on lib/docs/scrapers/react_bootstrap.rb
> +    options[:attribution] = <<-HTML
Please also add the license to `assets/javascripts/templates/pages/about_tmpl.coffee`

2021-02-23 05:53 UTC, dohsimpson commented on lib/docs/filters/react_bootstrap/clean_html.rb
> +    class CleanHtmlFilter < Filter
Hi @simon04 , thanks for the review, I have fixed the second bullet point, which is to remove most of the unnecessary classes. But I would like to keep the styling as "simple" please. As the default "simple" stylesheet looks pretty good in my opinion.

2021-02-26 07:28 UTC, simon04 approved these changes
Thank you!

2021-02-26 07:30 UTC, merged