Add Opengl documentation (gl4 + gl2.1)
freeCodeCamp/devdocs pull request #2136
Opened 2024-01-21 01:45 UTC by Suraj-Yadav

If you're adding a new scraper, please ensure that you have:

- [x] Tested the scraper on a local copy of DevDocs
- [x] Ensured that the docs are styled similarly to other docs on DevDocs

- [x] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [x] `16.png`: a 16×16 pixel icon for the doc
  - [x] `16@2x.png`: a 32×32 pixel icon for the doc
  - [x] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

2024-01-21 18:59 UTC, simon04 requested changes
Thank you for your work. Please see and address my comments.

2024-01-21 18:59 UTC, simon04 commented on lib/docs/scrapers/opengl.rb
> +    version 'gl4' do
Typically, we use version numbers w/o any prefixes. Can we drop `gl` for both versions?

2024-01-21 18:59 UTC, simon04 commented on lib/docs/scrapers/opengl.rb
> +      return 'v1.0.0'
This should be implemented correctly or omitted. You may want to extract the version from https://registry.khronos.org/OpenGL-Refpages/gl4/html/start.html, for instance.

2024-01-21 22:55 UTC, Suraj-Yadav commented on lib/docs/scrapers/opengl.rb
> +    Commons Attribution 4.0 International License</a>.
I have written logic to extract copyright from the page, but I am getting this warning 
`Docs::AttributionFilter is re-parsing the document.`
Unfortunately, I don't think there is any way to do this without parsing the document, as the value changes without any pattern in the URL.

2024-02-08 22:57 UTC, Suraj-Yadav commented
@simon04 I have implemented the requested changes.

2024-07-14 07:36 UTC, Suraj-Yadav commented
Hi @simon04, Can this be looked into again?

2024-07-28 08:51 UTC, simon04 approved these changes
Thank you!

2024-07-28 08:51 UTC, merged